# Default ChatFilter Config file
#
# debugMode: [true|false] Enable extra debug info in logs.
# kick: [true|false] Kick players after warning.
# showInConsole: [true|false] Show player and offending message in console.
#

debugMode: false

kick: false

showInConsole: true
