profanity:
- shit
- fuck
- piss
- cunt

profanityWordMatch:
- ass
- poo
- boob
- boobs
- crap

profanityMessage: "Oi %N! Mind your language!"

censorText: "!@$#"

triggers:
- eleven
- '11'

triggerPhrase: "That's ridiculous, it's not even funny."
