name: ChatFilter
main: me.sablednah.ChatFilter.ChatFilter
version: 1.7.1
description: Maintain a simple list of banned words.  
            Chat messages with these words are cancelled and the offender is sent a message.
            Also a list of words to trigger a public message.
            
            It`s ridiculous, it's not even funny!
commands:
    ChatFilter:
        description: Root command for all  ChatFilter Commands.
        usage: /<command> [reload]
        
permissions:
    chatfilter.*:
        description: Gives access to all MobHealth commands/functions.
        children:
            chatfilter.canswear: true
            chatfilter.reload: true
    chatfilter.canswear:
        description: Allows user to swear.
        default: false
    chatfilter.blockchat:
        description: Prevents user from swearing.
        default: false
    chatfilter.reload:
        description: Allows user to reload settings.
        default: op
        