name: ChatFilter
main: me.sablednah.ChatFilter.ChatFilter
version: 1.0
description: >
            Maintain a simple list of banned words.  
            Chat messages with these words are cancelled and the offender is sent a message.
            Also a list of words to trigger a public message.
            It`s rediculous, it's not even funny!
commands:
